export const FirestoreCollections = {
  USERS: "users",
  APPLICATIONS: "applications",
  MEDICAL_INTERESTS: "medical_interests",
  CIVIL_SERVICES_INTERESTS: "civil_services_interests",
  CONTACT_SUBMISSIONS: "contact_submissions",
  PROFESSIONAL_APPLICATIONS: "professional_course_applications",
  AI_LEADS: "ai_leads",
  ENROLLMENTS: "enrollments",
  JOBS: "jobs",
  MENTORS: "mentors",
} as const;

export const FirestoreDatabaseDesign = {
  users: {
    description: "Authentication-linked user profiles used by the website and professional portal.",
    docShape: {
      uid: "string",
      name: "string",
      email: "string",
      mobile: "string",
      userType: "student | parent | admin",
      platform: "academic | professional",
      applicationId: "string | null",
      applicationPath: "string | null",
      applicationStatus: "string",
      stream: "string",
      batchLevel: "string | null",
      tier: "string | null",
      createdAt: "serverTimestamp",
      updatedAt: "serverTimestamp",
    },
  },
  applications: {
    description: "Academic program applications created by students and parents.",
    docShape: {
      applicationId: "string",
      userId: "string",
      userType: "student | parent",
      applicantName: "string",
      studentName: "string",
      email: "string",
      status: "new | under_review | accepted | rejected",
      stream: "string",
      classApplying: "string",
      batchLevel: "string | null",
      tier: "string | null",
      createdAt: "serverTimestamp",
      updatedAt: "serverTimestamp",
    },
  },
  contact_submissions: {
    description: "Website contact form enquiries from students, parents, and general visitors.",
    docShape: {
      name: "string",
      email: "string",
      mobile: "string",
      userType: "student | parent | other",
      classLevel: "string",
      interestedIn: "string",
      message: "string",
      sourcePage: "contact",
      status: "new",
      consentGiven: "boolean",
      createdAt: "serverTimestamp",
      updatedAt: "serverTimestamp",
    },
  },
  professional_course_applications: {
    description: "Applications submitted from the professional website course pages.",
    docShape: {
      applicationId: "string",
      userId: "string | null",
      fullName: "string",
      email: "string",
      mobile: "string",
      city: "string",
      state: "string",
      educationLevel: "string",
      college: "string",
      degree: "string",
      graduationYear: "string",
      courseId: "string",
      courseName: "string",
      courseDuration: "string | null",
      courseFee: "number | null",
      emiPlan: "string | null",
      experienceLevel: "string",
      technicalExperience: "string",
      careerGoal: "string",
      applicationStatus: "new",
      paymentStatus: "pending",
      createdAt: "serverTimestamp",
      updatedAt: "serverTimestamp",
    },
  },
  ai_leads: {
    description: "Leads captured from the Junior Dream AI counsellor or supported discovery flows.",
    docShape: {
      leadId: "string",
      name: "string",
      email: "string",
      mobile: "string",
      userType: "string",
      recommendedCourses: "array",
      conversationSummary: "string",
      consentGiven: "boolean",
      status: "string",
      createdAt: "serverTimestamp",
      updatedAt: "serverTimestamp",
    },
  },
};
